export const TIMEZONES = [
  {gmt: 'GMT-12:00', name: 'Etc/GMT+12', shortHand: '-12'},
  {gmt: 'GMT-11:00', name: 'Etc/GMT+11', shortHand: '-11'},
  {gmt: 'GMT-11:00', name: 'Pacific/Midway', shortHand: 'SST'},
  {gmt: 'GMT-11:00', name: 'Pacific/Niue', shortHand: '-11'},
  {gmt: 'GMT-11:00', name: 'Pacific/Pago Pago', shortHand: 'SST'},
  {gmt: 'GMT-11:00', name: 'Pacific/Samoa', shortHand: 'SST'},
  {gmt: 'GMT-11:00', name: 'US/Samoa', shortHand: 'SST'},
  {gmt: 'GMT-10:00', name: 'Etc/GMT+10', shortHand: '-10'},
  {gmt: 'GMT-10:00', name: 'HST', shortHand: 'HST'},
  {gmt: 'GMT-10:00', name: 'Pacific/Honolulu', shortHand: 'HST'},
  {gmt: 'GMT-10:00', name: 'Pacific/Johnston', shortHand: 'HST'},
  {gmt: 'GMT-10:00', name: 'Pacific/Rarotonga', shortHand: '-10'},
  {gmt: 'GMT-10:00', name: 'Pacific/Tahiti', shortHand: '-10'},
  {gmt: 'GMT-10:00', name: 'US/Hawaii', shortHand: 'HST'},
  {gmt: 'GMT-09:30', name: 'Pacific/Marquesas', shortHand: '-0930'},
  {gmt: 'GMT-09:00', name: 'America/Adak', shortHand: 'HDT'},
  {gmt: 'GMT-09:00', name: 'America/Atka', shortHand: 'HDT'},
  {gmt: 'GMT-09:00', name: 'Etc/GMT+9', shortHand: '-09'},
  {gmt: 'GMT-09:00', name: 'Pacific/Gambier', shortHand: '-09'},
  {gmt: 'GMT-09:00', name: 'US/Aleutian', shortHand: 'HDT'},
  {gmt: 'GMT-08:00', name: 'America/Anchorage', shortHand: 'AKDT'},
  {gmt: 'GMT-08:00', name: 'America/Juneau', shortHand: 'AKDT'},
  {gmt: 'GMT-08:00', name: 'America/Metlakatla', shortHand: 'AKDT'},
  {gmt: 'GMT-08:00', name: 'America/Nome', shortHand: 'AKDT'},
  {gmt: 'GMT-08:00', name: 'America/Sitka', shortHand: 'AKDT'},
  {gmt: 'GMT-08:00', name: 'America/Yakutat', shortHand: 'AKDT'},
  {gmt: 'GMT-08:00', name: 'Etc/GMT+8', shortHand: '-08'},
  {gmt: 'GMT-08:00', name: 'Pacific/Pitcairn', shortHand: '-08'},
  {gmt: 'GMT-08:00', name: 'US/Alaska', shortHand: 'AKDT'},
  {gmt: 'GMT-07:00', name: 'America/Creston', shortHand: 'MST'},
  {gmt: 'GMT-07:00', name: 'America/Dawson', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'America/Dawson Creek', shortHand: 'MST'},
  {gmt: 'GMT-07:00', name: 'America/Ensenada', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'America/Fort Nelson', shortHand: 'MST'},
  {gmt: 'GMT-07:00', name: 'America/Hermosillo', shortHand: 'MST'},
  {gmt: 'GMT-07:00', name: 'America/Los Angeles', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'America/Phoenix', shortHand: 'MST'},
  {gmt: 'GMT-07:00', name: 'America/Santa Isabel', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'America/Tijuana', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'America/Vancouver', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'America/Whitehorse', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'Canada/Pacific', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'Canada/Yukon', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'Etc/GMT+7', shortHand: '-07'},
  {gmt: 'GMT-07:00', name: 'MST', shortHand: 'MST'},
  {gmt: 'GMT-07:00', name: 'Mexico/BajaNorte', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'PST8PDT', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'US/Arizona', shortHand: 'MST'},
  {gmt: 'GMT-07:00', name: 'US/Pacific', shortHand: 'PDT'},
  {gmt: 'GMT-07:00', name: 'US/Pacific-New', shortHand: 'PDT'},
  {gmt: 'GMT-06:00', name: 'America/Belize', shortHand: 'CST'},
  {gmt: 'GMT-06:00', name: 'America/Boise', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'America/Cambridge Bay', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'America/Chihuahua', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'America/Costa Rica', shortHand: 'CST'},
  {gmt: 'GMT-06:00', name: 'America/Denver', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'America/Edmonton', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'America/El Salvador', shortHand: 'CST'},
  {gmt: 'GMT-06:00', name: 'America/Guatemala', shortHand: 'CST'},
  {gmt: 'GMT-06:00', name: 'America/Inuvik', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'America/Managua', shortHand: 'CST'},
  {gmt: 'GMT-06:00', name: 'America/Mazatlan', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'America/Ojinaga', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'America/Regina', shortHand: 'CST'},
  {gmt: 'GMT-06:00', name: 'America/Shiprock', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'America/Swift Current', shortHand: 'CST'},
  {gmt: 'GMT-06:00', name: 'America/Tegucigalpa', shortHand: 'CST'},
  {gmt: 'GMT-06:00', name: 'America/Yellowknife', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'Canada/Mountain', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'Canada/Saskatchewan', shortHand: 'CST'},
  {gmt: 'GMT-06:00', name: 'Chile/EasterIsland', shortHand: '-06'},
  {gmt: 'GMT-06:00', name: 'Etc/GMT+6', shortHand: '-06'},
  {gmt: 'GMT-06:00', name: 'MST7MDT', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'Mexico/BajaSur', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'Navajo', shortHand: 'MDT'},
  {gmt: 'GMT-06:00', name: 'Pacific/Easter', shortHand: '-06'},
  {gmt: 'GMT-06:00', name: 'Pacific/Galapagos', shortHand: '-06'},
  {gmt: 'GMT-06:00', name: 'US/Mountain', shortHand: 'MDT'},
  {gmt: 'GMT-05:00', name: 'America/Atikokan', shortHand: 'EST'},
  {gmt: 'GMT-05:00', name: 'America/Bahia Banderas', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Bogota', shortHand: '-05'},
  {gmt: 'GMT-05:00', name: 'America/Cancun', shortHand: 'EST'},
  {gmt: 'GMT-05:00', name: 'America/Cayman', shortHand: 'EST'},
  {gmt: 'GMT-05:00', name: 'America/Chicago', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Coral Harbour', shortHand: 'EST'},
  {gmt: 'GMT-05:00', name: 'America/Eirunepe', shortHand: '-05'},
  {gmt: 'GMT-05:00', name: 'America/Guayaquil', shortHand: '-05'},
  {gmt: 'GMT-05:00', name: 'America/Indiana/Knox', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Indiana/Tell City', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Jamaica', shortHand: 'EST'},
  {gmt: 'GMT-05:00', name: 'America/Knox IN', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Lima', shortHand: '-05'},
  {gmt: 'GMT-05:00', name: 'America/Matamoros', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Menominee', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Merida', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Mexico City', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Monterrey', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/North Dakota/Beulah', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/North Dakota/Center', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/North Dakota/New Salem', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Panama', shortHand: 'EST'},
  {gmt: 'GMT-05:00', name: 'America/Porto Acre', shortHand: '-05'},
  {gmt: 'GMT-05:00', name: 'America/Rainy River', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Rankin Inlet', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Resolute', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'America/Rio Branco', shortHand: '-05'},
  {gmt: 'GMT-05:00', name: 'America/Winnipeg', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'Brazil/Acre', shortHand: '-05'},
  {gmt: 'GMT-05:00', name: 'CST6CDT', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'Canada/Central', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'EST', shortHand: 'EST'},
  {gmt: 'GMT-05:00', name: 'Etc/GMT+5', shortHand: '-05'},
  {gmt: 'GMT-05:00', name: 'Jamaica', shortHand: 'EST'},
  {gmt: 'GMT-05:00', name: 'Mexico/General', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'US/Central', shortHand: 'CDT'},
  {gmt: 'GMT-05:00', name: 'US/Indiana-Starke', shortHand: 'CDT'},
  {gmt: 'GMT-04:00', name: 'America/Anguilla', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Antigua', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Aruba', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Asuncion', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'America/Barbados', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Blanc-Sablon', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Boa Vista', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'America/Campo Grande', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'America/Caracas', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'America/Cuiaba', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'America/Curacao', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Detroit', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Dominica', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Fort Wayne', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Grand Turk', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Grenada', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Guadeloupe', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Guyana', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'America/Havana', shortHand: 'CDT'},
  {gmt: 'GMT-04:00', name: 'America/Indiana/Indianapolis', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Indiana/Marengo', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Indiana/Petersburg', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Indiana/Vevay', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Indiana/Vincennes', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Indiana/Winamac', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Indianapolis', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Iqaluit', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Kentucky/Louisville', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Kentucky/Monticello', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Kralendijk', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/La Paz', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'America/Louisville', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Lower Princes', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Manaus', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'America/Marigot', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Martinique', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Montreal', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Montserrat', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Nassau', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/New York', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Nipigon', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Pangnirtung', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Port-au-Prince', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Port of Spain', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Porto Velho', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'America/Puerto Rico', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Santiago', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'America/Santo Domingo', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/St Barthelemy', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/St Kitts', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/St Lucia', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/St Thomas', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/St Vincent', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Thunder Bay', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Toronto', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'America/Tortola', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'America/Virgin', shortHand: 'AST'},
  {gmt: 'GMT-04:00', name: 'Brazil/West', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'Canada/Eastern', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'Chile/Continental', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'Cuba', shortHand: 'CDT'},
  {gmt: 'GMT-04:00', name: 'EST5EDT', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'Etc/GMT+4', shortHand: '-04'},
  {gmt: 'GMT-04:00', name: 'US/East-Indiana', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'US/Eastern', shortHand: 'EDT'},
  {gmt: 'GMT-04:00', name: 'US/Michigan', shortHand: 'EDT'},
  {gmt: 'GMT-03:00', name: 'America/Araguaina', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/Buenos Aires', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/Catamarca', shortHand: '-03'},
  {
    gmt: 'GMT-03:00',
    name: 'America/Argentina/ComodRivadavia',
    shortHand: '-03'
  },
  {gmt: 'GMT-03:00', name: 'America/Argentina/Cordoba', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/Jujuy', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/La Rioja', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/Mendoza', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/Rio Gallegos', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/Salta', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/San Juan', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/San Luis', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/Tucuman', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Argentina/Ushuaia', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Bahia', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Belem', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Buenos Aires', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Catamarca', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Cayenne', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Cordoba', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Fortaleza', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Glace Bay', shortHand: 'ADT'},
  {gmt: 'GMT-03:00', name: 'America/Goose Bay', shortHand: 'ADT'},
  {gmt: 'GMT-03:00', name: 'America/Halifax', shortHand: 'ADT'},
  {gmt: 'GMT-03:00', name: 'America/Jujuy', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Maceio', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Mendoza', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Moncton', shortHand: 'ADT'},
  {gmt: 'GMT-03:00', name: 'America/Montevideo', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Paramaribo', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Punta Arenas', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Recife', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Rosario', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Santarem', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Sao Paulo', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'America/Thule', shortHand: 'ADT'},
  {gmt: 'GMT-03:00', name: 'Antarctica/Palmer', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'Antarctica/Rothera', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'Atlantic/Bermuda', shortHand: 'ADT'},
  {gmt: 'GMT-03:00', name: 'Atlantic/Stanley', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'Brazil/East', shortHand: '-03'},
  {gmt: 'GMT-03:00', name: 'Canada/Atlantic', shortHand: 'ADT'},
  {gmt: 'GMT-03:00', name: 'Etc/GMT+3', shortHand: '-03'},
  {gmt: 'GMT-02:30', name: 'America/St Johns', shortHand: 'NDT'},
  {gmt: 'GMT-02:30', name: 'Canada/Newfoundland', shortHand: 'NDT'},
  {gmt: 'GMT-02:00', name: 'America/Godthab', shortHand: '-02'},
  {gmt: 'GMT-02:00', name: 'America/Miquelon', shortHand: '-02'},
  {gmt: 'GMT-02:00', name: 'America/Noronha', shortHand: '-02'},
  {gmt: 'GMT-02:00', name: 'Atlantic/South Georgia', shortHand: '-02'},
  {gmt: 'GMT-02:00', name: 'Brazil/DeNoronha', shortHand: '-02'},
  {gmt: 'GMT-02:00', name: 'Etc/GMT+2', shortHand: '-02'},
  {gmt: 'GMT-01:00', name: 'Atlantic/Cape Verde', shortHand: '-01'},
  {gmt: 'GMT-01:00', name: 'Etc/GMT+1', shortHand: '-01'},
  {gmt: 'GMT+00:00', name: 'Africa/Abidjan', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Accra', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Bamako', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Banjul', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Bissau', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Conakry', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Dakar', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Freetown', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Lome', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Monrovia', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Nouakchott', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Ouagadougou', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Sao Tome', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Africa/Timbuktu', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'America/Danmarkshavn', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'America/Scoresbysund', shortHand: '+00'},
  {gmt: 'GMT+00:00', name: 'Atlantic/Azores', shortHand: '+00'},
  {gmt: 'GMT+00:00', name: 'Atlantic/Reykjavik', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Atlantic/St Helena', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Etc/GMT', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Etc/GMT+0', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Etc/GMT-0', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Etc/GMT0', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Etc/Greenwich', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Etc/UCT', shortHand: 'UTC'},
  {gmt: 'GMT+00:00', name: 'Etc/UTC', shortHand: 'UTC'},
  {gmt: 'GMT+00:00', name: 'Etc/Universal', shortHand: 'UTC'},
  {gmt: 'GMT+00:00', name: 'Etc/Zulu', shortHand: 'UTC'},
  {gmt: 'GMT+00:00', name: 'GMT', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'GMT+0', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'GMT-0', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'GMT0', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Greenwich', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'Iceland', shortHand: 'GMT'},
  {gmt: 'GMT+00:00', name: 'UCT', shortHand: 'UTC'},
  {gmt: 'GMT+00:00', name: 'UTC', shortHand: 'UTC'},
  {gmt: 'GMT+00:00', name: 'Universal', shortHand: 'UTC'},
  {gmt: 'GMT+00:00', name: 'Zulu', shortHand: 'UTC'},
  {gmt: 'GMT+01:00', name: 'Africa/Algiers', shortHand: 'CET'},
  {gmt: 'GMT+01:00', name: 'Africa/Bangui', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/Brazzaville', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/Casablanca', shortHand: '+01'},
  {gmt: 'GMT+01:00', name: 'Africa/Douala', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/El Aaiun', shortHand: '+01'},
  {gmt: 'GMT+01:00', name: 'Africa/Kinshasa', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/Lagos', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/Libreville', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/Luanda', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/Malabo', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/Ndjamena', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/Niamey', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/Porto-Novo', shortHand: 'WAT'},
  {gmt: 'GMT+01:00', name: 'Africa/Tunis', shortHand: 'CET'},
  {gmt: 'GMT+01:00', name: 'Atlantic/Canary', shortHand: 'WEST'},
  {gmt: 'GMT+01:00', name: 'Atlantic/Faeroe', shortHand: 'WEST'},
  {gmt: 'GMT+01:00', name: 'Atlantic/Faroe', shortHand: 'WEST'},
  {gmt: 'GMT+01:00', name: 'Atlantic/Madeira', shortHand: 'WEST'},
  {gmt: 'GMT+01:00', name: 'Eire', shortHand: 'IST'},
  {gmt: 'GMT+01:00', name: 'Etc/GMT-1', shortHand: '+01'},
  {gmt: 'GMT+01:00', name: 'Europe/Belfast', shortHand: 'BST'},
  {gmt: 'GMT+01:00', name: 'Europe/Dublin', shortHand: 'IST'},
  {gmt: 'GMT+01:00', name: 'Europe/Guernsey', shortHand: 'BST'},
  {gmt: 'GMT+01:00', name: 'Europe/Isle of Man', shortHand: 'BST'},
  {gmt: 'GMT+01:00', name: 'Europe/Jersey', shortHand: 'BST'},
  {gmt: 'GMT+01:00', name: 'Europe/Lisbon', shortHand: 'WEST'},
  {gmt: 'GMT+01:00', name: 'Europe/London', shortHand: 'BST'},
  {gmt: 'GMT+01:00', name: 'GB', shortHand: 'BST'},
  {gmt: 'GMT+01:00', name: 'GB-Eire', shortHand: 'BST'},
  {gmt: 'GMT+01:00', name: 'Portugal', shortHand: 'WEST'},
  {gmt: 'GMT+01:00', name: 'WET', shortHand: 'WEST'},
  {gmt: 'GMT+02:00', name: 'Africa/Blantyre', shortHand: 'CAT'},
  {gmt: 'GMT+02:00', name: 'Africa/Bujumbura', shortHand: 'CAT'},
  {gmt: 'GMT+02:00', name: 'Africa/Cairo', shortHand: 'EET'},
  {gmt: 'GMT+02:00', name: 'Africa/Ceuta', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Africa/Gaborone', shortHand: 'CAT'},
  {gmt: 'GMT+02:00', name: 'Africa/Harare', shortHand: 'CAT'},
  {gmt: 'GMT+02:00', name: 'Africa/Johannesburg', shortHand: 'SAST'},
  {gmt: 'GMT+02:00', name: 'Africa/Khartoum', shortHand: 'CAT'},
  {gmt: 'GMT+02:00', name: 'Africa/Kigali', shortHand: 'CAT'},
  {gmt: 'GMT+02:00', name: 'Africa/Lubumbashi', shortHand: 'CAT'},
  {gmt: 'GMT+02:00', name: 'Africa/Lusaka', shortHand: 'CAT'},
  {gmt: 'GMT+02:00', name: 'Africa/Maputo', shortHand: 'CAT'},
  {gmt: 'GMT+02:00', name: 'Africa/Maseru', shortHand: 'SAST'},
  {gmt: 'GMT+02:00', name: 'Africa/Mbabane', shortHand: 'SAST'},
  {gmt: 'GMT+02:00', name: 'Africa/Tripoli', shortHand: 'EET'},
  {gmt: 'GMT+02:00', name: 'Africa/Windhoek', shortHand: 'CAT'},
  {gmt: 'GMT+02:00', name: 'Antarctica/Troll', shortHand: '+02'},
  {gmt: 'GMT+02:00', name: 'Arctic/Longyearbyen', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Atlantic/Jan Mayen', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'CET', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Egypt', shortHand: 'EET'},
  {gmt: 'GMT+02:00', name: 'Etc/GMT-2', shortHand: '+02'},
  {gmt: 'GMT+02:00', name: 'Europe/Amsterdam', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Andorra', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Belgrade', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Berlin', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Bratislava', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Brussels', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Budapest', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Busingen', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Copenhagen', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Gibraltar', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Kaliningrad', shortHand: 'EET'},
  {gmt: 'GMT+02:00', name: 'Europe/Ljubljana', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Luxembourg', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Madrid', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Malta', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Monaco', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Oslo', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Paris', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Podgorica', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Prague', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Rome', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/San Marino', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Sarajevo', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Skopje', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Stockholm', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Tirane', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Vaduz', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Vatican', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Vienna', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Warsaw', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Zagreb', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Europe/Zurich', shortHand: 'CEST'},
  {gmt: 'GMT+02:00', name: 'Libya', shortHand: 'EET'},
  {gmt: 'GMT+02:00', name: 'MET', shortHand: 'MEST'},
  {gmt: 'GMT+02:00', name: 'Poland', shortHand: 'CEST'},
  {gmt: 'GMT+03:00', name: 'Africa/Addis Ababa', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Africa/Asmara', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Africa/Asmera', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Africa/Dar es Salaam', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Africa/Djibouti', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Africa/Juba', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Africa/Kampala', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Africa/Mogadishu', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Africa/Nairobi', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Antarctica/Syowa', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Asia/Aden', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Asia/Amman', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Asia/Baghdad', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Asia/Bahrain', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Asia/Beirut', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Asia/Damascus', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Asia/Famagusta', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Asia/Gaza', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Asia/Hebron', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Asia/Istanbul', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Asia/Jerusalem', shortHand: 'IDT'},
  {gmt: 'GMT+03:00', name: 'Asia/Kuwait', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Asia/Nicosia', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Asia/Qatar', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Asia/Riyadh', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Asia/Tel Aviv', shortHand: 'IDT'},
  {gmt: 'GMT+03:00', name: 'EET', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Etc/GMT-3', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Europe/Athens', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Bucharest', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Chisinau', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Helsinki', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Istanbul', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Europe/Kiev', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Kirov', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Europe/Mariehamn', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Minsk', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'Europe/Moscow', shortHand: 'MSK'},
  {gmt: 'GMT+03:00', name: 'Europe/Nicosia', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Riga', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Simferopol', shortHand: 'MSK'},
  {gmt: 'GMT+03:00', name: 'Europe/Sofia', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Tallinn', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Tiraspol', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Uzhgorod', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Vilnius', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Europe/Zaporozhye', shortHand: 'EEST'},
  {gmt: 'GMT+03:00', name: 'Indian/Antananarivo', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Indian/Comoro', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Indian/Mayotte', shortHand: 'EAT'},
  {gmt: 'GMT+03:00', name: 'Israel', shortHand: 'IDT'},
  {gmt: 'GMT+03:00', name: 'Turkey', shortHand: '+03'},
  {gmt: 'GMT+03:00', name: 'W-SU', shortHand: 'MSK'},
  {gmt: 'GMT+04:00', name: 'Asia/Baku', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Asia/Dubai', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Asia/Muscat', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Asia/Tbilisi', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Asia/Yerevan', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Etc/GMT-4', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Europe/Astrakhan', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Europe/Samara', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Europe/Saratov', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Europe/Ulyanovsk', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Europe/Volgograd', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Indian/Mahe', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Indian/Mauritius', shortHand: '+04'},
  {gmt: 'GMT+04:00', name: 'Indian/Reunion', shortHand: '+04'},
  {gmt: 'GMT+04:30', name: 'Asia/Kabul', shortHand: '+0430'},
  {gmt: 'GMT+04:30', name: 'Asia/Tehran', shortHand: '+0430'},
  {gmt: 'GMT+04:30', name: 'Iran', shortHand: '+0430'},
  {gmt: 'GMT+05:00', name: 'Antarctica/Mawson', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Aqtau', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Aqtobe', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Ashgabat', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Ashkhabad', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Atyrau', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Dushanbe', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Karachi', shortHand: 'PKT'},
  {gmt: 'GMT+05:00', name: 'Asia/Oral', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Qyzylorda', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Samarkand', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Tashkent', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Asia/Yekaterinburg', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Etc/GMT-5', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Indian/Kerguelen', shortHand: '+05'},
  {gmt: 'GMT+05:00', name: 'Indian/Maldives', shortHand: '+05'},
  {gmt: 'GMT+05:30', name: 'Asia/Calcutta', shortHand: 'IST'},
  {gmt: 'GMT+05:30', name: 'Asia/Colombo', shortHand: '+0530'},
  {gmt: 'GMT+05:30', name: 'Asia/Kolkata', shortHand: 'IST'},
  {gmt: 'GMT+05:45', name: 'Asia/Kathmandu', shortHand: '+0545'},
  {gmt: 'GMT+05:45', name: 'Asia/Katmandu', shortHand: '+0545'},
  {gmt: 'GMT+06:00', name: 'Antarctica/Vostok', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Asia/Almaty', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Asia/Bishkek', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Asia/Dacca', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Asia/Dhaka', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Asia/Kashgar', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Asia/Omsk', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Asia/Qostanay', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Asia/Thimbu', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Asia/Thimphu', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Asia/Urumqi', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Etc/GMT-6', shortHand: '+06'},
  {gmt: 'GMT+06:00', name: 'Indian/Chagos', shortHand: '+06'},
  {gmt: 'GMT+06:30', name: 'Asia/Rangoon', shortHand: '+0630'},
  {gmt: 'GMT+06:30', name: 'Asia/Yangon', shortHand: '+0630'},
  {gmt: 'GMT+06:30', name: 'Indian/Cocos', shortHand: '+0630'},
  {gmt: 'GMT+07:00', name: 'Antarctica/Davis', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Bangkok', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Barnaul', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Ho Chi Minh', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Hovd', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Jakarta', shortHand: 'WIB'},
  {gmt: 'GMT+07:00', name: 'Asia/Krasnoyarsk', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Novokuznetsk', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Novosibirsk', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Phnom Penh', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Pontianak', shortHand: 'WIB'},
  {gmt: 'GMT+07:00', name: 'Asia/Saigon', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Tomsk', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Asia/Vientiane', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Etc/GMT-7', shortHand: '+07'},
  {gmt: 'GMT+07:00', name: 'Indian/Christmas', shortHand: '+07'},
  {gmt: 'GMT+08:00', name: 'Antarctica/Casey', shortHand: '+08'},
  {gmt: 'GMT+08:00', name: 'Asia/Brunei', shortHand: '+08'},
  {gmt: 'GMT+08:00', name: 'Asia/Choibalsan', shortHand: '+08'},
  {gmt: 'GMT+08:00', name: 'Asia/Chongqing', shortHand: 'CST'},
  {gmt: 'GMT+08:00', name: 'Asia/Chungking', shortHand: 'CST'},
  {gmt: 'GMT+08:00', name: 'Asia/Harbin', shortHand: 'CST'},
  {gmt: 'GMT+08:00', name: 'Asia/Hong Kong', shortHand: 'HKT'},
  {gmt: 'GMT+08:00', name: 'Asia/Irkutsk', shortHand: '+08'},
  {gmt: 'GMT+08:00', name: 'Asia/Kuala Lumpur', shortHand: '+08'},
  {gmt: 'GMT+08:00', name: 'Asia/Kuching', shortHand: '+08'},
  {gmt: 'GMT+08:00', name: 'Asia/Macao', shortHand: 'CST'},
  {gmt: 'GMT+08:00', name: 'Asia/Macau', shortHand: 'CST'},
  {gmt: 'GMT+08:00', name: 'Asia/Makassar', shortHand: 'WITA'},
  {gmt: 'GMT+08:00', name: 'Asia/Manila', shortHand: 'PST'},
  {gmt: 'GMT+08:00', name: 'Asia/Shanghai', shortHand: 'CST'},
  {gmt: 'GMT+08:00', name: 'Asia/Singapore', shortHand: '+08'},
  {gmt: 'GMT+08:00', name: 'Asia/Taipei', shortHand: 'CST'},
  {gmt: 'GMT+08:00', name: 'Asia/Ujung Pandang', shortHand: 'WITA'},
  {gmt: 'GMT+08:00', name: 'Asia/Ulaanbaatar', shortHand: '+08'},
  {gmt: 'GMT+08:00', name: 'Asia/Ulan Bator', shortHand: '+08'},
  {gmt: 'GMT+08:00', name: 'Australia/Perth', shortHand: 'AWST'},
  {gmt: 'GMT+08:00', name: 'Australia/West', shortHand: 'AWST'},
  {gmt: 'GMT+08:00', name: 'Etc/GMT-8', shortHand: '+08'},
  {gmt: 'GMT+08:00', name: 'Hongkong', shortHand: 'HKT'},
  {gmt: 'GMT+08:00', name: 'PRC', shortHand: 'CST'},
  {gmt: 'GMT+08:00', name: 'ROC', shortHand: 'CST'},
  {gmt: 'GMT+08:00', name: 'Singapore', shortHand: '+08'},
  {gmt: 'GMT+08:45', name: 'Australia/Eucla', shortHand: '+0845'},
  {gmt: 'GMT+09:00', name: 'Asia/Chita', shortHand: '+09'},
  {gmt: 'GMT+09:00', name: 'Asia/Dili', shortHand: '+09'},
  {gmt: 'GMT+09:00', name: 'Asia/Jayapura', shortHand: 'WIT'},
  {gmt: 'GMT+09:00', name: 'Asia/Khandyga', shortHand: '+09'},
  {gmt: 'GMT+09:00', name: 'Asia/Pyongyang', shortHand: 'KST'},
  {gmt: 'GMT+09:00', name: 'Asia/Seoul', shortHand: 'KST'},
  {gmt: 'GMT+09:00', name: 'Asia/Tokyo', shortHand: 'JST'},
  {gmt: 'GMT+09:00', name: 'Asia/Yakutsk', shortHand: '+09'},
  {gmt: 'GMT+09:00', name: 'Etc/GMT-9', shortHand: '+09'},
  {gmt: 'GMT+09:00', name: 'Japan', shortHand: 'JST'},
  {gmt: 'GMT+09:00', name: 'Pacific/Palau', shortHand: '+09'},
  {gmt: 'GMT+09:00', name: 'ROK', shortHand: 'KST'},
  {gmt: 'GMT+09:30', name: 'Australia/Adelaide', shortHand: 'ACST'},
  {gmt: 'GMT+09:30', name: 'Australia/Broken Hill', shortHand: 'ACST'},
  {gmt: 'GMT+09:30', name: 'Australia/Darwin', shortHand: 'ACST'},
  {gmt: 'GMT+09:30', name: 'Australia/North', shortHand: 'ACST'},
  {gmt: 'GMT+09:30', name: 'Australia/South', shortHand: 'ACST'},
  {gmt: 'GMT+09:30', name: 'Australia/Yancowinna', shortHand: 'ACST'},
  {gmt: 'GMT+10:00', name: 'Antarctica/DumontDUrville', shortHand: '+10'},
  {gmt: 'GMT+10:00', name: 'Asia/Ust-Nera', shortHand: '+10'},
  {gmt: 'GMT+10:00', name: 'Asia/Vladivostok', shortHand: '+10'},
  {gmt: 'GMT+10:00', name: 'Australia/ACT', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/Brisbane', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/Canberra', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/Currie', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/Hobart', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/Lindeman', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/Melbourne', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/NSW', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/Queensland', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/Sydney', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/Tasmania', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Australia/Victoria', shortHand: 'AEST'},
  {gmt: 'GMT+10:00', name: 'Etc/GMT-10', shortHand: '+10'},
  {gmt: 'GMT+10:00', name: 'Pacific/Chuuk', shortHand: '+10'},
  {gmt: 'GMT+10:00', name: 'Pacific/Guam', shortHand: 'ChST'},
  {gmt: 'GMT+10:00', name: 'Pacific/Port Moresby', shortHand: '+10'},
  {gmt: 'GMT+10:00', name: 'Pacific/Saipan', shortHand: 'ChST'},
  {gmt: 'GMT+10:00', name: 'Pacific/Truk', shortHand: '+10'},
  {gmt: 'GMT+10:00', name: 'Pacific/Yap', shortHand: '+10'},
  {gmt: 'GMT+10:30', name: 'Australia/LHI', shortHand: '+1030'},
  {gmt: 'GMT+10:30', name: 'Australia/Lord Howe', shortHand: '+1030'},
  {gmt: 'GMT+11:00', name: 'Antarctica/Macquarie', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Asia/Magadan', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Asia/Sakhalin', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Asia/Srednekolymsk', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Etc/GMT-11', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Pacific/Bougainville', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Pacific/Efate', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Pacific/Guadalcanal', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Pacific/Kosrae', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Pacific/Norfolk', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Pacific/Noumea', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Pacific/Pohnpei', shortHand: '+11'},
  {gmt: 'GMT+11:00', name: 'Pacific/Ponape', shortHand: '+11'},
  {gmt: 'GMT+12:00', name: 'Antarctica/McMurdo', shortHand: 'NZST'},
  {gmt: 'GMT+12:00', name: 'Antarctica/South Pole', shortHand: 'NZST'},
  {gmt: 'GMT+12:00', name: 'Asia/Anadyr', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'Asia/Kamchatka', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'Etc/GMT-12', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'Kwajalein', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'NZ', shortHand: 'NZST'},
  {gmt: 'GMT+12:00', name: 'Pacific/Auckland', shortHand: 'NZST'},
  {gmt: 'GMT+12:00', name: 'Pacific/Fiji', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'Pacific/Funafuti', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'Pacific/Kwajalein', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'Pacific/Majuro', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'Pacific/Nauru', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'Pacific/Tarawa', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'Pacific/Wake', shortHand: '+12'},
  {gmt: 'GMT+12:00', name: 'Pacific/Wallis', shortHand: '+12'},
  {gmt: 'GMT+12:45', name: 'NZ-CHAT', shortHand: '+1245'},
  {gmt: 'GMT+12:45', name: 'Pacific/Chatham', shortHand: '+1245'},
  {gmt: 'GMT+13:00', name: 'Etc/GMT-13', shortHand: '+13'},
  {gmt: 'GMT+13:00', name: 'Pacific/Apia', shortHand: '+13'},
  {gmt: 'GMT+13:00', name: 'Pacific/Enderbury', shortHand: '+13'},
  {gmt: 'GMT+13:00', name: 'Pacific/Fakaofo', shortHand: '+13'},
  {gmt: 'GMT+13:00', name: 'Pacific/Tongatapu', shortHand: '+13'},
  {gmt: 'GMT+14:00', name: 'Etc/GMT-14', shortHand: '+14'},
  {gmt: 'GMT+14:00', name: 'Pacific/Kiritimati', shortHand: '+14'}
]
