export const FORMULA_CONSTANTS = [
  {name: 'e', resultType: 'number'},
  {name: 'pi', resultType: 'number'},
  {name: 'true', resultType: 'checkbox'},
  {name: 'false', resultType: 'checkbox'}
]

export const FORMULA_OPERATORS = [
  {name: 'if', resultType: 'text'},
  {name: 'add', resultType: 'number'},
  {name: 'subtract', resultType: 'number'},
  {name: 'multiply', resultType: 'number'},
  {name: 'divide', resultType: 'number'},
  {name: 'pow', resultType: 'number'},
  {name: 'mod', resultType: 'number'},
  {name: 'unaryMinus', resultType: 'number'},
  {name: 'unaryPlus', resultType: 'number'},
  {name: 'not', resultType: 'checkbox'},
  {name: 'and', resultType: 'checkbox'},
  {name: 'or', resultType: 'checkbox'},
  {name: 'equal', resultType: 'checkbox'},
  {name: 'unequal', resultType: 'checkbox'},
  {name: 'larger', resultType: 'checkbox'},
  {name: 'largerEq', resultType: 'checkbox'},
  {name: 'smaller', resultType: 'checkbox'},
  {name: 'smallerEq', resultType: 'checkbox'}
]

export const FORMULA_FUNCTIONS = [
  {name: 'concat', resultType: 'ctext'},
  {name: 'join', resultType: 'ctext'},
  {name: 'slice', resultType: 'ctext'},
  {name: 'length', resultType: 'number'},
  {name: 'format', resultType: 'ctext'},
  {name: 'toNumber', resultType: 'number'},
  {name: 'contains', resultType: 'checkbox'},
  {name: 'replace', resultType: 'ctext'},
  {name: 'replaceAll', resultType: 'ctext'},
  {name: 'test', resultType: 'checkbox'},
  {name: 'empty', resultType: 'checkbox'},
  {name: 'abs', resultType: 'number'},
  {name: 'cbrt', resultType: 'number'},
  {name: 'ceil', resultType: 'number'},
  {name: 'exp', resultType: 'number'},
  {name: 'floor', resultType: 'number'},
  {name: 'ln', resultType: 'number'},
  {name: 'log10', resultType: 'number'},
  {name: 'log2', resultType: 'number'},
  {name: 'max', resultType: 'number'},
  {name: 'min', resultType: 'number'},
  {name: 'round', resultType: 'number'},
  {name: 'sign', resultType: 'number'},
  {name: 'sqrt', resultType: 'number'},
  {name: 'start', resultType: 'date'},
  {name: 'end', resultType: 'date'},
  {name: 'now', resultType: 'date'},
  {name: 'timestamp', resultType: 'number'},
  {name: 'fromTimestamp', resultType: 'date'},
  {name: 'dateAdd', resultType: 'date'},
  {name: 'dateSubtract', resultType: 'date'},
  {name: 'dateBetween', resultType: 'number'},
  {name: 'formatDate', resultType: 'ctext'},
  {name: 'minute', resultType: 'number'},
  {name: 'hour', resultType: 'number'},
  {name: 'day', resultType: 'number'},
  {name: 'date', resultType: 'number'},
  {name: 'month', resultType: 'number'},
  {name: 'year', resultType: 'number'}
]
